version: 2.1

jobs:
  install-deps:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies
  lsif-node:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc packages/**/*.js --allowJs --checkJs
      - run: src lsif upload -no-progress

workflows:
  lsif-node:
    jobs:
      - install-deps
      - lsif-node:
          requires:
            - install-deps
